config/routes.rb
Rails.application.routes.draw do
  resources :props, only: [:index, :new, :create,:show,:edit,:update, :destroy]
  root to: "props#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prop.rb
class Prop < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50}
  validates :rent, numericality: { only_integer: true }, allow_blank: true
  validates :address, presence: true, length: { minimum: 5, maximum: 255}
  validates :years_old, numericality: { only_integer: true }, length: { maximum: 3}, allow_blank: true
  validates :comment, length: { maximum: 300 }
  has_many :stations, dependent: :destroy
  accepts_nested_attributes_for :stations
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :prop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
before_action :set_prop, only: [:show,:edit,:update,:destroy]

  def index
    @props = Prop.all
  end

  def new
    @prop = Prop.new
    2.times{ @prop.stations.build }
  end

  def create
    @prop = Prop.new(prop_params)
    if @prop.save
      redirect_to props_path
      flash[:notice] = "物件を登録しました。"
    else
      render :new
    end
  end

  def show
  end

  def edit
    @prop.stations.build
  end

  def update
    if @prop.update(prop_params)
      redirect_to props_path
      flash[:notice] = "物件を編集しました。"
    else
      render :edit
    end
  end

  def destroy
    @prop.destroy
    redirect_to props_path
    flash[:notice] = "物件を削除しました。"
  end

  private

  def prop_params
    params.require(:prop).permit(:name,:address,:rent,:years_old,:comment,stations_attributes:[:line_name,:station_name,:minutes,:id])
  end

  def set_prop
    @prop = Prop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/props_helper.rb
module PropsHelper
  def presence_or_not_display(data)
    if data
      data
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Property</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/props/_form.html.erb
<% if @prop.errors.any? %>
  <div class="error_display">
    <% @prop.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
    <% end %>
  </div>
<% end %>
<%= form_with(model:@prop, local:true) do |form| %>
  <div class="prop_form">
    <p><%= form.label :name %></p>
    <p><%= form.text_field :name %></p>
    <p><%= form.label :address %></p>
    <p><%= form.text_field :address %></p>
    <p><%= form.label :rent %></p>
    <p><%= form.text_field :rent %></p>
    <p><%= form.label :years_old %></p>
    <p><%= form.text_field :years_old %></p>
    <p><%= form.label :comment %></p>
    <p><%= form.text_area :comment %></p>
  </div>
  <div class="stations_form">
    <% count = 0 %>
    <%= form.fields_for :stations do |s|%>
      <% count += 1 %>
      <h3>最寄り駅<%= count %></h3>
      <p><%= s.label :line_name %></p>
      <p><%= s.text_field :line_name %></p>
      <p><%= s.label :station_name %></p>
      <p><%= s.text_field :station_name %></p>
      <p><%= s.label :minutes %></p>
      <p><%= s.text_field :minutes %></p>
    <% end %>
  </div>
  <p><%= form.submit "登録する" %></p>
<% end %>

app/views/props/edit.html.erb
<h1>物件編集</h1>

<%= render 'form' %>
<p><%= link_to "詳細", prop_path(@prop.id) %>|<%= link_to "戻る", props_path %></p>

app/views/props/index.html.erb
<h1>物件一覧</h1>
<%= link_to "新規登録", new_prop_path %>
<table class="properties">
  <tr>
    <th>物件名</th><th>賃料</th><th>住所</th><th>築年数</th><th>備考</th>
  </tr>
  <% @props.each do |prop| %>
    <tr>
      <td><%= prop.name %></td><td><% if presence_or_not_display(prop.rent) %><%= prop.rent.to_s(:delimited) %>円<% end %></td><td><%= prop.address %></td><td><% if presence_or_not_display(prop.years_old) %><%= prop.years_old %>年<% end %></td><td><%= presence_or_not_display(prop.comment) %></td><td><%= link_to "詳細", prop_path(prop.id) %></td><td><%= link_to "編集", edit_prop_path(prop.id) %></td><td><%= button_to "削除", prop_path(prop.id),method: :delete, data: {confirm: "本当に削除しますか？"}, class:"delete_button" %></td>
    </tr>
  <% end %>
</table>

app/views/props/new.html.erb
<h1>物件登録</h1>
<%= render 'form' %>
<p><%= link_to "一覧に戻る", props_path %></p>
<p><%= link_to "戻る", props_path %></p>

app/views/props/show.html.erb
<p><span class="show_label">物件名:</span><%= @prop.name %></p>
<p><span class="show_label">賃料:</span><% if presence_or_not_display(@prop.rent) %><%= @prop.rent.to_s(:delimited) %>円<% end %></p>
<p><span class="show_label">住所:</span><%= @prop.address %></p>
<p><span class="show_label">築年数:</span><% if presence_or_not_display(@prop.years_old) %><%= @prop.years_old %>年<% end %></p>
<p><span class="show_label">備考:</span></p>
<p><%= presence_or_not_display(@prop.comment) %></p>
<div class="show_stations">
  <% count = 0 %>
  <% @prop.stations.each do |station| %>
    <% count += 1 %>
    <h3>最寄り駅<%= count %></h3>
    <p><span class="show_label">路線名:</span><%= station.line_name %></p>
    <p><span class="show_label">駅名:</span><%= station.station_name %></p>
    <p><span class="show_label">徒歩分数:</span><%= station.minutes %></p>
  <% end %>
</div>
<div class="bottom_link">
  <%= link_to "編集", edit_prop_path(@prop.id) %> | <%= link_to "戻る", props_path %>
</div>